<!DOCTYPE html>
<html>
<body>
<table>
    <tr>
        <th>number order</th>
        <th>{{$number_order}}</th>
    </tr>
    <tr>
        <td>name</td>
        <td>{{$name}}</td>
    </tr>
    <tr>
        <td>address</td>
        <td>{{$address}}</td>
    </tr>
    <tr>
        <td>mobile</td>
        <td>{{$mobile}}</td>
    </tr>
    <tr>
        <td>total_cost</td>
        <td>{{$total_cost}}</td>
    </tr>
    <tr>
        <td>cost_delivery</td>
        <td>{{$cost_delivery}}</td>
    </tr>
    <tr>
        <td>total</td>
        <td>{{$total}}</td>
    </tr>
    <tr>
        <td>notes</td>
        <td>{{$notes}}</td>
    </tr>
</table>
</body>
</html>